vpc-name      = "Jenkins-VPC"
igw-name      = "Jenkins-IGW"
subnet-name   = "Jenkins-SUBNET"
rt-name       = "Jenkins-ROUTETABLE"
sg-name       = "Jenkins-SG"
instance-name = "Jenkins-SERVER"
Key-name      = "likitha"
Aim-role      = "Jenkins-aim-role"
